In [2]:
import numpy as np
import pandas as pd

In [3]:
dataset = pd.read_csv("50_Startups.csv")

In [4]:
dataset.head(10)

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94
5  131876.90        99814.71        362861.36    New York  156991.12
6  134615.46       147198.87              NaN  California  156122.51
7  130298.13       145530.06        323876.68     Florida  155752.60
8  120542.52       148718.95        311613.29    New York  152211.77
9  123334.88       108679.17        304981.62  California  149759.96

In [5]:
dataset.isnull().any()

R&D Spend          False
Administration      True
Marketing Spend     True
State              False
Profit             False
dtype: bool

In [6]:
dataset.isnull().sum()

R&D Spend          0
Administration     1
Marketing Spend    1
State              0
Profit             0
dtype: int64

In [7]:
dataset["Administration"].mean()

121564.03816326526

In [8]:
dataset["Marketing Spend"].mean()

212725.26673469393

In [9]:
dataset["Administration"].fillna(dataset["Administration"].mean(),inplace = True)
dataset["Marketing Spend"].fillna(dataset["Marketing Spend"].mean(),inplace = True)

In [10]:
dataset.isnull().any()

R&D Spend          False
Administration     False
Marketing Spend    False
State              False
Profit             False
dtype: bool

All the null values have been filled

In [11]:
x= dataset.iloc[:,0:4].values
y= dataset.iloc[:,4:].values

In [12]:
x.shape

(50, 4)

In [13]:
y.shape


(50, 1)

In [14]:
dataset.head(1)

R&D Spend  Administration  Marketing Spend     State     Profit
0   165349.2        136897.8         471784.1  New York  192261.83

In [15]:
dataset["State"].unique()
# we can expect to have 3 new colums after the column transformation

array(['New York', 'California', 'Florida'], dtype=object)

In [16]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [17]:
ct = ColumnTransformer([("one",OneHotEncoder(),[3])],remainder = "passthrough")
x = ct.fit_transform(x)

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 0)

In [19]:
from sklearn.preprocessing import StandardScaler
s = StandardScaler()
x_train = s.fit_transform(x_train)
x_test = s.fit_transform(x_test)

In [20]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
regression = Sequential()

In [21]:
# input
regression.add(Dense(units=6, kernel_initializer="random_uniform", activation="relu"))
#hidden layers
regression.add(Dense(units=12, kernel_initializer = "random_uniform", activation="relu"))
regression.add(Dense(units=12, kernel_initializer = "random_uniform", activation="relu"))
regression.add(Dense(units=12, kernel_initializer = "random_uniform", activation="relu"))
# output layers
regression.add(Dense(units=1, kernel_initializer = "random_uniform", activation="relu"))

In [22]:
regression.compile(optimizer="rmsprop", loss="mse" ,metrics=["mse"])

In [23]:
regression.fit(x_train, y_train, epochs = 1000)

Epoch 1/1000
2/2 [==============================] - 1s 2ms/step - loss: 13615994880.0000 - mse: 13615994880.0000
Epoch 2/1000
2/2 [==============================] - 0s 2ms/step - loss: 13615994880.0000 - mse: 13615994880.0000
Epoch 3/1000
2/2 [==============================] - 0s 3ms/step - loss: 13615991808.0000 - mse: 13615991808.0000
Epoch 4/1000
2/2 [==============================] - 0s 2ms/step - loss: 13615991808.0000 - mse: 13615991808.0000
Epoch 5/1000
2/2 [==============================] - 0s 2ms/step - loss: 13615991808.0000 - mse: 13615991808.0000
Epoch 6/1000
2/2 [==============================] - 0s 3ms/step - loss: 13615989760.0000 - mse: 13615989760.0000
Epoch 7/1000
2/2 [==============================] - 0s 2ms/step - loss: 13615988736.0000 - mse: 13615988736.0000
Epoch 8/1000
2/2 [==============================] - 0s 3ms/step - loss: 13615988736.0000 - mse: 13615988736.0000
Epoch 9/1000
2/2 [==============================] - 0s 3ms/step - loss: 13615986688.0000 - mse: 

In [25]:
ypred = regression.predict(x_test)

In [26]:
ypred

array([[ 79452.   ],
       [ 77652.484],
       [ 81556.414],
       [ 51054.105],
       [146701.72 ],
       [129208.64 ],
       [ 28966.441],
       [ 70654.8  ],
       [ 77550.625],
       [116092.805]], dtype=float32)

In [28]:
y_test

array([[103282.38],
       [144259.4 ],
       [146121.95],
       [ 77798.83],
       [191050.39],
       [105008.31],
       [ 81229.06],
       [ 97483.56],
       [110352.25],
       [166187.94]])

Predicting individual rows

In [33]:
dataset.head(10)


R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80    471784.100000    New York  192261.83
1  162597.70       151377.59    443898.530000  California  191792.06
2  153441.51       101145.55    407934.540000     Florida  191050.39
3  144372.41       118671.85    383199.620000    New York  182901.99
4  142107.34        91391.77    366168.420000     Florida  166187.94
5  131876.90        99814.71    362861.360000    New York  156991.12
6  134615.46       147198.87    212725.266735  California  156122.51
7  130298.13       145530.06    323876.680000     Florida  155752.60
8  120542.52       148718.95    311613.290000    New York  152211.77
9  123334.88       108679.17    304981.620000  California  149759.96

In [31]:
yp = regression.predict(s.transform(ct.transform([[123334.88,108679.17,304981.620000,'California']])))

In [32]:
yp

array([[99773.03]], dtype=float32)